"use client";
import { useCallback, useEffect, useRef, useState } from "react";
import { Mic, MicOff, PhoneOff, Video, VideoOff } from "lucide-react";
import toast from "react-hot-toast";

const iceServers: RTCIceServer[] = [{ urls: process.env.NEXT_PUBLIC_WEBRTC_STUN_URL || "stun:stun.l.google.com:19302" }, ...(process.env.NEXT_PUBLIC_WEBRTC_TURN_URL ? [{ urls: process.env.NEXT_PUBLIC_WEBRTC_TURN_URL, username: process.env.NEXT_PUBLIC_WEBRTC_TURN_USERNAME, credential: process.env.NEXT_PUBLIC_WEBRTC_TURN_CREDENTIAL }] : [])];
export function InternalCallDialog({ chatSessionId, userId, otherName, mode, incoming, onClose }: { chatSessionId: string; userId: string; otherName: string; mode: "voice"|"video"; incoming?: any; onClose: () => void }) {
  const pc = useRef<RTCPeerConnection|null>(null), media = useRef<MediaStream|null>(null), callId = useRef(incoming?.$id || ""), pending = useRef<RTCIceCandidateInit[]>([]), added = useRef(new Set<string>());
  const local = useRef<HTMLVideoElement>(null), remote = useRef<HTMLVideoElement>(null); const [status,setStatus]=useState(incoming?"Incoming call":"Calling…"), [accepted,setAccepted]=useState(!incoming), [muted,setMuted]=useState(false), [cameraOff,setCameraOff]=useState(false);
  const api = async (body:any) => { const res=await fetch("/api/internal-calls",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({...body,userId})}); const data=await res.json(); if(!res.ok) throw new Error(data.error); return data; };
  const stop = useCallback(async (remoteEnd=false,statusValue="ended") => { if(!remoteEnd && callId.current) await api({action:"status",callId:callId.current,status:statusValue}).catch(()=>{}); pc.current?.close(); media.current?.getTracks().forEach(t=>t.stop()); onClose(); },[onClose,userId]);
  const begin = useCallback(async()=>{ try { setAccepted(true); media.current=await navigator.mediaDevices.getUserMedia({audio:true,video:mode==="video"}); if(local.current)local.current.srcObject=media.current; const peer=new RTCPeerConnection({iceServers}); pc.current=peer; media.current.getTracks().forEach(t=>peer.addTrack(t,media.current!)); peer.ontrack=e=>{if(remote.current)remote.current.srcObject=e.streams[0];setStatus("Connected");}; const sendCandidate=(c:RTCIceCandidateInit)=>api({action:"candidate",callId:callId.current,candidate:c.candidate,sdpMid:c.sdpMid,sdpMLineIndex:c.sdpMLineIndex}).catch(()=>{}); peer.onicecandidate=e=>{if(!e.candidate)return; const c=e.candidate.toJSON(); if(callId.current)void sendCandidate(c); else pending.current.push(c);}; if(incoming){await peer.setRemoteDescription({type:"offer",sdp:incoming.offerSdp});const answer=await peer.createAnswer();await peer.setLocalDescription(answer);await api({action:"status",callId:callId.current,status:"accepted",answerSdp:answer.sdp});setStatus("Connecting…");}else{const offer=await peer.createOffer();await peer.setLocalDescription(offer);const data=await api({action:"create",chatSessionId,mode,offerSdp:offer.sdp});callId.current=data.call.$id;for(const candidate of pending.current.splice(0))void sendCandidate(candidate);} } catch(e:any){toast.error(e?.message||"Allow microphone and camera access.");void stop(false,"declined");}},[chatSessionId,incoming,mode,stop,userId]);
  useEffect(()=>{if(!incoming)void begin(); const timer=setInterval(async()=>{if(!callId.current)return; const res=await fetch(`/api/internal-calls?callId=${callId.current}&userId=${userId}`,{cache:"no-store"});const data=await res.json();if(!res.ok)return;const call=data.call;if(!incoming&&call.status==="accepted"&&call.answerSdp&&pc.current&&!pc.current.remoteDescription){await pc.current.setRemoteDescription({type:"answer",sdp:call.answerSdp});setStatus("Connecting…");}for(const row of data.candidates||[]){if(row.senderId===userId||added.current.has(row.$id)||!pc.current?.remoteDescription)continue;added.current.add(row.$id);await pc.current.addIceCandidate({candidate:row.candidate,sdpMid:row.sdpMid||null,sdpMLineIndex:Number(row.sdpMLineIndex||0)}).catch(()=>{});}["ended","declined","missed"].includes(call.status)&&void stop(true);},1200);return()=>clearInterval(timer);},[begin,incoming,stop,userId]);
  return <div className="fixed inset-0 z-[100] grid place-items-center bg-slate-950/75 p-4 backdrop-blur-sm"><div className="relative flex min-h-[430px] w-full max-w-2xl flex-col overflow-hidden rounded-lg bg-slate-950 text-white shadow-2xl"><video ref={remote} autoPlay playsInline className={`absolute inset-0 size-full object-cover ${mode==="video"?"block":"hidden"}`}/><div className="relative z-10 flex flex-1 flex-col items-center justify-center bg-slate-950/55"><div className="grid size-20 place-items-center rounded-full bg-blue-600 text-2xl font-bold">{otherName.slice(0,2).toUpperCase()}</div><h2 className="mt-4 text-xl font-bold">{otherName}</h2><p className="mt-1 text-sm text-slate-300">{status}</p>{mode==="video"&&<video ref={local} autoPlay muted playsInline className="absolute bottom-4 right-4 h-36 w-24 rounded-md border border-white/20 object-cover"/>}</div><div className="relative z-20 flex justify-center gap-3 border-t border-white/10 p-5">{incoming&&!accepted?<><button onClick={()=>void stop(false,"declined")} className="grid size-12 place-items-center rounded-full bg-red-600"><PhoneOff/></button><button onClick={()=>void begin()} className="h-12 rounded-full bg-emerald-600 px-6 font-bold">Answer</button></>:<><button onClick={()=>{const n=!muted;media.current?.getAudioTracks().forEach(t=>t.enabled=!n);setMuted(n)}} className="grid size-11 place-items-center rounded-full bg-white/10">{muted?<MicOff/>:<Mic/>}</button>{mode==="video"&&<button onClick={()=>{const n=!cameraOff;media.current?.getVideoTracks().forEach(t=>t.enabled=!n);setCameraOff(n)}} className="grid size-11 place-items-center rounded-full bg-white/10">{cameraOff?<VideoOff/>:<Video/>}</button>}<button onClick={()=>void stop()} className="grid size-12 place-items-center rounded-full bg-red-600"><PhoneOff/></button></>}</div></div></div>;
}
